## Travis CI configuration file
## YAML v1.1
language: node_js

## Version control
git:
  depth: 1
  #sparse_checkout: skip-worktree-map-file
branches:
  only:
    - master
  except:
    - gh-pages

## Scripts
before_install: nvm install "$(jq -r '.engines.node' package.json)" ## https://github.com/travis-ci/travis-ci/issues/4653#issuecomment-276949979
install: npm install
before_script: false
script: npm run clean && npm run make
before_cache: false
#after_success: npm run deploy
after_failure: npm run clean
deploy: false
after_deploy: false
after_script: false
